# This file was generated by GoReleaser. DO NOT EDIT.
class Popeye < Formula
  desc "A Kubernetes Cluster sanitizer and linter."
  homepage "https://imhotep.io/popeye"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/derailed/popeye/releases/download/v0.5.0/popeye_0.5.0_Darwin_x86_64.tar.gz"
    sha256 "de96ac8e3c68a34d5c0f5d8f4b7f5746b28d7225e1cf266066b3cb4f953d42a3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/derailed/popeye/releases/download/v0.5.0/popeye_0.5.0_Linux_x86_64.tar.gz"
      sha256 "a0c2cf9f4dc3d431cefa79708ea6d3d0eead2b62ac5f5ee70f37cc2d651a62a7"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/derailed/popeye/releases/download/v0.5.0/popeye_0.5.0_Linux_arm64.tar.gz"
        sha256 "4a77b42c3c4862ddc3c9dc0f9a2e0687431fda9f68b0187beebe59bea36bed7e"
      else
        url "https://github.com/derailed/popeye/releases/download/v0.5.0/popeye_0.5.0_Linux_armv6.tar.gz"
        sha256 "689c8effbae5ea4bd57c5ec313c28647c8ea0082f037897a8b1503372dc1689a"
      end
    end
  end

  def install
    bin.install "popeye"
  end

  test do
    system "popeye version"
  end
end
