# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Popeye < Formula
  desc "A Kubernetes Cluster sanitizer and linter."
  homepage "https://imhotep.io/popeye"
  version "0.9.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/derailed/popeye/releases/download/v0.9.1/popeye_Darwin_x86_64.tar.gz"
    sha256 "5698e4c874082154b40ae656f402b751e961d94e028ef9c03bfae6c932be6e2c"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/derailed/popeye/releases/download/v0.9.1/popeye_Darwin_arm64.tar.gz"
    sha256 "9d1b18d573668f2d7413d0bcbe2cf80c7f1f0f609fd70e8cb3d989ef557e5ab6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/derailed/popeye/releases/download/v0.9.1/popeye_Linux_x86_64.tar.gz"
    sha256 "0885bee2a333759adc5bb0033a79bb58669968ec6a28910371d2204b052c0b25"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/derailed/popeye/releases/download/v0.9.1/popeye_Linux_arm64.tar.gz"
    sha256 "ffbc4fba2232ac8ab1738b173ce9cec21fab8adb18f1275c07695de0c9f50568"
  end

  def install
    bin.install "popeye"
  end

  test do
    system "popeye version"
  end
end
