# This file was generated by GoReleaser. DO NOT EDIT.
class Popeye < Formula
  desc "A Kubernetes Cluster sanitizer and linter."
  homepage "https://imhotep.io/popeye"
  url "https://github.com/derailed/popeye/releases/download/v0.1.4/popeye_0.1.4_Darwin_x86_64.tar.gz"
  version "0.1.4"
  sha256 "3ceeb098a6028401c0148a38b2797db73f6ef8e120e47f057c9be30db6cad27c"

  def install
    bin.install "popeye"
  end

  test do
    system "popeye version"
  end
end
